spring:
  application:
    name: lifecycle
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
      file-size-threshold: 1MB
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/lifecycle
      username: root
      password: cqh.123
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      removeAbandoned: false  #禁用对于长时间不使用的连接强制关闭的功能
      removeAbandonedTimeout: 1800 #超过30分钟开始关闭空闲连接，由于removeAbandoned为false，这个设置项不再起作用
      logAbandoned: true #将当前关闭动作记录到日志，由于removeAbandoned为false，这个设置项不再起作用


server:
  servlet:
    context-path: /lifecycle


mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: com.ch.model
  type-handlers-package: com.ch.mybatis


currentuserfilter:
  ignorePaths:
    -  /health
    -  /swagger-resources/**
    -  /webjars/springfox-swagger-ui/**
    -  /swagger-ui.html
    -  /v2/api-docs
    -  /login/sendLoginVerificationCode
    -  /login/registerAndLogin

